server:
  port: 8085
  application:
    name: CONFIG-SERVER

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ppsingh32/microservice-config
          clone-on-start: true



