server:
  port: 8082

spring:
  application:
    name: HOTEL-SERVICE
  data:
    mongodb:
      auto-index-creation: true
      database: hotelservice
      uri: mongodb://localhost:27017
  config:
    import: optional:configserver:http://localhost:8085



#eureka:
#  instance:
#    appname: HOTEL-SERVICE
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: DEBUG